<a href="https://colab.research.google.com/github/shake345/pre_treatment/blob/main/pre_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
import pandas as pd
%cd /content/drive/MyDrive/前処理大全/

/content/drive/MyDrive/前処理大全

In [29]:
reserve_tb = pd.read_csv('reserve.csv', encoding='utf-8')

In [30]:
# 必要なカラムを抽出
reserve_tb[['reserve_id','hotel_id','customer_id','reserve_datetime','checkin_date','checkin_time','checkout_date']]
print(reserve_tb.head())

  reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0         r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1         r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2         r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3         r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4         r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22

  checkin_time checkout_date  people_num  total_price
0     10:00:00    2016-03-29           4        97200
1     11:30:00    2016-07-21           2        20600
2     09:00:00    2016-10-22           2        33600
3     11:00:00    2017-03-30           4       194400
4     10:30:00    2017-09-23           3        68100

In [31]:
# 条件による抽出
query_table = reserve_tb.query('"2016-10-12" <= checkout_date <= "2016-10-13"')
query_table.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
347,r348,h_161,c_82,2016-09-22 22:29:52,2016-10-10,10:30:00,2016-10-12,2,178400
587,r588,h_263,c_143,2016-09-25 20:07:03,2016-10-11,09:00:00,2016-10-12,4,91600
1254,r1255,h_148,c_305,2016-09-12 15:32:03,2016-10-11,11:30:00,2016-10-12,4,39200
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13,4,107200
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13,2,153600

In [32]:
# ランダムサンプリング
samp_table = reserve_tb.sample(frac=0.5)
samp_table

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
11,r12,h_268,c_2,2017-05-24 10:06:21,2017-06-20,09:00:00,2017-06-21,4,81600
568,r569,h_124,c_135,2016-08-11 23:59:06,2016-08-20,10:00:00,2016-08-21,2,133200
145,r146,h_294,c_30,2016-03-31 02:38:28,2016-04-22,09:30:00,2016-04-23,1,40100
1961,r1962,h_195,c_486,2016-12-30 08:46:53,2017-01-15,11:00:00,2017-01-17,4,401600
3201,r3202,h_93,c_805,2016-07-17 15:17:41,2016-08-06,11:30:00,2016-08-09,1,29400
...,...,...,...,...,...,...,...,...,...
3289,r3290,h_104,c_826,2017-02-27 11:22:48,2017-03-19,11:30:00,2017-03-22,2,253200
1417,r1418,h_122,c_345,2016-08-07 15:45:08,2016-08-12,12:00:00,2016-08-14,2,26800
2925,r2926,h_74,c_738,2017-02-10 08:58:39,2017-02-25,09:30:00,2017-02-26,3,14400
111,r112,h_70,c_22,2017-04-07 13:08:25,2017-04-27,09:30:00,2017-04-28,3,23400
2283,r2284,h_99,c_573,2016-10-28 04:27:28,2016-11-22,12:00:00,2016-11-25,1,67200

In [33]:
# IDごとのサンプリング
# sample関数を利用するために、pd.Series（pandasのリストオブジェクト）に変換
target = pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)
reserve_tb[reserve_tb['customer_id'].isin(target)]
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100

In [34]:
# カウントとユニークカウント
# reserve_idを対象にcount関数を適用
# customer_idを対象にnunique関数を適用
result = reserve_tb.groupby('hotel_id').agg({'reserve_id': 'count', 'customer_id':'nunique'})

result.reset_index(inplace=True)
result.columns = ['hotel_id','rsv_cnt', 'cus_cnt']
result.head()

  hotel_id  rsv_cnt  cus_cnt
0      h_1       10       10
1     h_10        3        3
2    h_100       20       19
3    h_101       17       17
4    h_102       13       13

In [35]:
# 合計値
result_sum = reserve_tb.groupby(['hotel_id','people_num'])['total_price'].sum().reset_index()

result_sum.rename(columns={'total_price': 'price_sum'}, inplace=True)
result_sum.head()

  hotel_id  people_num  price_sum
0      h_1           1     156600
1      h_1           2     156600
2      h_1           3     391500
3      h_1           4     417600
4     h_10           1      11200

In [36]:
# 代表値
import numpy as np
result_value = reserve_tb.groupby('hotel_id').agg({'total_price': ['max','min','mean','median',lambda x: np.percentile(x, q=20)]}).reset_index()

result_value.columns = ['hotel_id',' price_max', 'price_min', 'price_mean', 'price_median', 'price_20per']
result_value.head()

  hotel_id   price_max  price_min     price_mean  price_median  price_20per
0      h_1      208800      26100  112230.000000      104400.0      73080.0
1     h_10       67200      11200   42933.333333       50400.0      26880.0
2    h_100       57600       4800   27600.000000       28800.0       9600.0
3    h_101      168000      14000   75764.705882       56000.0      30800.0
4    h_102       72000      12000   32769.230769       24000.0      18000.0

In [37]:
# 分散地と標準偏差値
result_var_std = reserve_tb.groupby('hotel_id').agg({'total_price': ['var','std']}).reset_index()
result_var_std.columns = ['hotel_id','price_var','price_std']

# データ件が1件の場合は、分散地と標準偏差値がnaになっているので、0に置き換える
result_var_std.fillna(0, inplace=True)
result_var_std.head()

  hotel_id     price_var     price_std
0      h_1  3.186549e+09  56449.526127
1     h_10  8.258133e+08  28736.968061
2    h_100  3.198316e+08  17883.835689
3    h_101  2.402441e+09  49014.703676
4    h_102  3.576923e+08  18912.755159

In [38]:
# 最頻値の算出
reserve_tb['total_price'].round(-3).mode()

0    10000
1    20000
2    40000
Name: total_price, dtype: int64

In [39]:
# 順位の算出
# rank関数は文字列に対応していないため、datetime型に変換
reserve_tb['reserve_datetime'] = pd.to_datetime(reserve_tb['reserve_datetime'], format='%Y-%m-%d %H:%M:%S')

# method='first': 同率は登録順にランク付けされる
reserve_tb['log_no'] = reserve_tb.groupby('customer_id')['reserve_datetime'].rank(ascending=True,method='first')
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0

In [40]:
# ランキング
reserve_rank = reserve_tb.groupby('hotel_id').size().reset_index()
reserve_rank.columns = ['hotel_id','rsv_cnt']

# method='min':同率は同じランク（最小単位）を付与
reserve_rank['rsv_cnt_rank'] = reserve_rank['rsv_cnt'].rank(ascending=False, method='min')
reserve_rank = reserve_rank[['hotel_id','rsv_cnt_rank']]

In [41]:
reserve_rank_sorted = reserve_rank.sort_values(by='rsv_cnt_rank', ascending=True)
display(reserve_rank_sorted.head())

    hotel_id  rsv_cnt_rank
158    h_241           1.0
50     h_144           2.0
231     h_37           3.0
48     h_142           3.0
87     h_178           5.0

In [42]:
# マスタテーブルの結合
hotel_tb = pd.read_csv('hotel.csv', encoding='utf-8')
display(hotel_tb.head())

pd.merge(reserve_tb.query('people_num==1'), hotel_tb.query('is_business'), on='hotel_id', how='inner')

,hotel_id,base_price,big_area_name,small_area_name,hotel_latitude,hotel_longitude,is_business
0,h_1,26100,D,D-2,43.064569,141.511397,True
1,h_2,26400,A,A-1,35.715320,139.939446,True
2,h_3,41300,E,E-4,35.281572,136.988565,False
3,h_4,5200,C,C-3,38.431293,140.795615,False
4,h_5,13500,G,G-3,33.597291,130.533872,True

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,base_price,big_area_name,small_area_name,hotel_latitude,hotel_longitude,is_business
0,r7,h_256,c_1,2017-12-29 10:38:36,2018-01-25,10:30:00,2018-01-28,1,103500,7.0,34500,C,C-1,38.237294,140.696131,True
1,r11,h_183,c_2,2016-11-19 12:49:10,2016-12-08,11:00:00,2016-12-11,1,29700,3.0,9900,G,G-4,33.595248,130.633567,True
2,r13,h_223,c_2,2017-10-19 03:03:30,2017-10-21,09:30:00,2017-10-23,1,137000,5.0,68500,C,C-2,38.329097,140.698165,True
3,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13,1,20400,2.0,20400,C,C-1,38.231842,140.797268,True
4,r25,h_277,c_4,2016-03-28 07:17:34,2016-04-07,10:30:00,2016-04-10,1,39300,1.0,13100,C,C-1,38.233985,140.795603,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,r3999,h_72,c_993,2016-06-09 04:35:48,2016-07-04,12:00:00,2016-07-07,1,29100,2.0,9700,B,B-2,35.545712,139.596157,True
442,r4001,h_253,c_993,2017-01-20 18:50:35,2017-02-10,11:00:00,2017-02-12,1,10400,4.0,5200,C,C-3,38.430220,140.696571,True
443,r4005,h_150,c_994,2016-03-25 11:51:26,2016-04-02,09:00:00,2016-04-03,1,25200,1.0,25200,B,B-2,35.546229,139.693687,True
444,r4011,h_137,c_995,2017-08-13 19:23:48,2017-09-07,09:30:00,2017-09-09,1,12400,6.0,6200,F,F-1,34.538252,132.469507,True
445,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,14700,A,A-3,35.912979,139.832314,True

In [43]:
# 条件別に結合するマスタテーブルを切り替え
hotel_area_tb = hotel_tb.groupby(['big_area_name','small_area_name']).size().reset_index()
hotel_area_tb.columns = ['big_area_name','small_area_name','hotel_cnt']
display(hotel_area_tb)

# 自ホテルを除いてhotel_cntが20以上の場合はsmall_area_name, それ以外の場合はbig_area_nameを付与したい
hotel_area_tb['join_area_id'] = np.where(hotel_area_tb['hotel_cnt'] -1 >= 20, hotel_area_tb['small_area_name'], hotel_area_tb['big_area_name'])
hotel_area_tb = hotel_area_tb[['small_area_name','join_area_id']]
display(hotel_area_tb.head())

   big_area_name small_area_name  hotel_cnt
0              A             A-1         35
1              A             A-3         30
2              B             B-1         15
3              B             B-2         18
4              B             B-3         19
5              C             C-1         25
6              C             C-2         30
7              C             C-3         21
8              D             D-1          7
9              D             D-2          7
10             D             D-3          7
11             D             D-4          5
12             E             E-1          8
13             E             E-2          5
14             E             E-3          4
15             E             E-4          9
16             F             F-1          6
17             F             F-2          5
18             F             F-3         11
19             F             F-4          7
20             G             G-1          9
21             G             G-2          4
22             G             G-3          6
23             G             G-4          7

  small_area_name join_area_id
0             A-1          A-1
1             A-3          A-3
2             B-1            B
3             B-2            B
4             B-3            B

In [44]:
base_hotel_mst = pd.merge(hotel_tb, hotel_area_tb, on='small_area_name')
base_hotel_mst = base_hotel_mst[['hotel_id','join_area_id']]
display(base_hotel_mst.head())

  hotel_id join_area_id
0      h_1            D
1      h_2          A-1
2      h_3            E
3      h_4          C-3
4      h_5            G

In [45]:
recommend_hotel_mst = pd.concat([
    # join_area_idをsmall_area_nameとしたマスタテーブル
    hotel_tb[['small_area_name','hotel_id']].rename(columns={'small_area_name': 'join_area_id'}, inplace=False),
    # join_area_idをbig_area_nameとしたマスタテーブル,
    hotel_tb[['big_area_name','hotel_id']].rename(columns={'big_area_name': 'join_area_id'}, inplace=False)
])

recommend_hotel_mst.rename(columns={'hotel_id': 'rec_hotel_id'}, inplace=True)

pd.merge(base_hotel_mst, recommend_hotel_mst, on='join_area_id').loc[:, ['hotel_id', 'rec_hotel_id']].query('hotel_id != rec_hotel_id')

     hotel_id rec_hotel_id
1         h_1         h_14
2         h_1         h_22
3         h_1         h_27
4         h_1         h_40
5         h_1         h_45
...       ...          ...
9658    h_300        h_247
9659    h_300        h_256
9660    h_300        h_257
9661    h_300        h_277
9662    h_300        h_295

[9364 rows x 2 columns]

In [46]:
# n件前のデータ取得
# groupby関数の後にapply関数を適用することで、groupごとの並び替えが可能
customer_reserve = reserve_tb.groupby('customer_id').apply(lambda x: x.sort_values(by='reserve_datetime', axis=0, inplace=False))
display(customer_reserve.head())

/tmp/ipykernel_4544/400148677.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  customer_reserve = reserve_tb.groupby('customer_id').apply(lambda x: x.sort_values(by='reserve_datetime', axis=0, inplace=False))

              reserve_id hotel_id customer_id    reserve_datetime  \
customer_id
c_1         0         r1     h_75         c_1 2016-03-06 13:09:42
            1         r2    h_219         c_1 2016-07-16 23:39:55
            2         r3    h_179         c_1 2016-09-24 10:03:17
            3         r4    h_214         c_1 2017-03-08 03:20:10
            4         r5     h_16         c_1 2017-09-05 19:50:37

              checkin_date checkin_time checkout_date  people_num  \
customer_id
c_1         0   2016-03-26     10:00:00    2016-03-29           4
            1   2016-07-20     11:30:00    2016-07-21           2
            2   2016-10-19     09:00:00    2016-10-22           2
            3   2017-03-29     11:00:00    2017-03-30           4
            4   2017-09-22     10:30:00    2017-09-23           3

               total_price  log_no
customer_id
c_1         0        97200     1.0
            1        20600     2.0
            2        33600     3.0
            3       194400     4.0
            4        68100     5.0

In [47]:
# shift関数は、periodsの引数の数だけデータ行を下にずらす関数
customer_reserve['before_price'] = pd.Series(customer_reserve['total_price'].shift(periods=2))
display(customer_reserve.head())

              reserve_id hotel_id customer_id    reserve_datetime  \
customer_id
c_1         0         r1     h_75         c_1 2016-03-06 13:09:42
            1         r2    h_219         c_1 2016-07-16 23:39:55
            2         r3    h_179         c_1 2016-09-24 10:03:17
            3         r4    h_214         c_1 2017-03-08 03:20:10
            4         r5     h_16         c_1 2017-09-05 19:50:37

              checkin_date checkin_time checkout_date  people_num  \
customer_id
c_1         0   2016-03-26     10:00:00    2016-03-29           4
            1   2016-07-20     11:30:00    2016-07-21           2
            2   2016-10-19     09:00:00    2016-10-22           2
            3   2017-03-29     11:00:00    2017-03-30           4
            4   2017-09-22     10:30:00    2017-09-23           3

               total_price  log_no  before_price
customer_id
c_1         0        97200     1.0           NaN
            1        20600     2.0           NaN
            2        33600     3.0       97200.0
            3       194400     4.0       20600.0
            4        68100     5.0       33600.0

In [48]:
# 過去n件の合計値
reserve_tb['price_sum'] = pd.Series(
    reserve_tb.groupby('customer_id')
    .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True))
    .loc[:, 'total_price']
    # rolling関数は、データをWindow（複数のデータ集合）に区切る関数
    # window引数で、自分を含め何件のデータに区切るのか設定
    # min_periods引数で、設定した件数以上を満たしたときのみ計算する。満たない時はNanとする。
    # center=Trueにすると、自データが真ん中になるように区切られる
    .rolling(center=False, window=3, min_periods=3).sum()
    .reset_index(drop=True)
)
display(reserve_tb)

/tmp/ipykernel_4544/2148315526.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True))

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,price_sum
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,NaN
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,NaN
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,151400.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,248600.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,296100.0
...,...,...,...,...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,217800.0
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,159000.0
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,112600.0
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13,4,540000,1.0,95000.0
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,132600.0

In [49]:
# 過去n回の平均値
reserve_tb['price_avg'] = pd.Series(
    reserve_tb.groupby('customer_id')
    .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True))
    .loc[:, 'total_price']
    # rolling関数は自身の行を基準に選択してしまうため、shift関数で1行ずらす
    .shift(1).rolling(window=3, min_periods=1).mean()
    .reset_index(drop=True)
)
display(reserve_tb)

/tmp/ipykernel_4544/1015835953.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True))

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,price_sum,price_avg
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,NaN,NaN
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,NaN,97200.000000
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,151400.0,58900.000000
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,248600.0,50466.666667
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,296100.0,82866.666667
...,...,...,...,...,...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,217800.0,139066.666667
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,159000.0,72600.000000
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,112600.0,53000.000000
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13,4,540000,1.0,95000.0,37533.333333
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,132600.0,31666.666667

In [50]:
# 過去n回の合計値
reserve_tb = reserve_tb.sort_values(["customer_id", "reserve_datetime"])

rolling_sum = (
    reserve_tb.set_index("reserve_datetime")
    .groupby("customer_id")["total_price"]
    .rolling("90D")
    .sum()
    .reset_index()
)

# 「過去」の合計にしたいので、今回の予約の金額（自分自身）を差し引く
rolling_sum["total_price_sum"] = (
    rolling_sum["total_price"] - reserve_tb["total_price"].values
)

# 元のテーブルに結果を結合（ソート順が一致しているので、そのまま代入可能）
reserve_tb["total_price_90d"] = rolling_sum["total_price_sum"].values

display(reserve_tb)

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,price_sum,price_avg,total_price_90d
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,NaN,NaN,0.0
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,NaN,97200.000000,0.0
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,151400.0,58900.000000,20600.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,248600.0,50466.666667,0.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,296100.0,82866.666667,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023,r4024,h_244,c_999,2016-10-06 18:01:34,2016-10-07,11:30:00,2016-10-09,3,59400,2.0,410200.0,116733.333333,0.0
4024,r4025,h_160,c_999,2017-03-11 11:56:05,2017-03-27,10:00:00,2017-03-30,1,37200,3.0,417200.0,136733.333333,0.0
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,217800.0,139066.666667,0.0
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,159000.0,72600.000000,0.0
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,112600.0,53000.000000,0.0

In [51]:
# 全結合処理
customer_tb = pd.read_csv('customer.csv', encoding='utf-8')
display(customer_tb.head())

  customer_id  age    sex  home_latitude  home_longitude
0         c_1   41    man      35.092193      136.512347
1         c_2   38    man      35.325076      139.410551
2         c_3   49  woman      35.120543      136.511179
3         c_4   43    man      43.034868      141.240314
4         c_5   31    man      35.102661      136.523797

In [52]:
import datetime
from dateutil.relativedelta import relativedelta

# 年月マスタの生成
month_mst = pd.DataFrame({
    'year_month':
    # relativedeltaで2017-01-01をx月間進める、xは0,1,2を代入
    # 2017-01-01, 2017-02-01, 2017-03-01のリストを生成
    [(datetime.date(2017,1,1) + relativedelta(months=x)).strftime('%Y%m')
    for x in range(0, 3)]
})

# cross_joinのために全て同じ値の結合キーを準備
customer_tb['join_key'] = 0
month_mst['join_key'] = 0

customer_mst = pd.merge(
    customer_tb[['customer_id','join_key']], month_mst, on='join_key'
)

display(customer_mst.head())

  customer_id  join_key year_month
0         c_1         0     201701
1         c_1         0     201702
2         c_1         0     201703
3         c_2         0     201701
4         c_2         0     201702

In [54]:
# 年月の結合キーを予約テーブルで準備
reserve_tb['year_month'] = reserve_tb['checkin_date'].apply(lambda x: pd.to_datetime(x, format='%Y-%m-%d').strftime('%Y%m'))

# 予約コードと結合し、合計利用金額を計算
summary_result = pd.merge(
    customer_mst,
    reserve_tb[['customer_id','year_month','total_price']],
    on=['customer_id','year_month'], how='left'
).groupby(['customer_id','year_month'])['total_price'].sum().reset_index()

# 予約レコードがなかった場合の合計金額を0に変換
summary_result.fillna(0, inplace=True)

display(summary_result)

     customer_id year_month  total_price
0            c_1     201701          0.0
1            c_1     201702          0.0
2            c_1     201703     194400.0
3           c_10     201701          0.0
4           c_10     201702          0.0
...          ...        ...          ...
2995       c_998     201702          0.0
2996       c_998     201703          0.0
2997       c_999     201701          0.0
2998       c_999     201702          0.0
2999       c_999     201703      37200.0

[3000 rows x 3 columns]

In [ ]:
# 交差検証：データをいくつかに分断し、分断した一つのデータ群をモデルの評価用のデータとして利用し、そのほかのデータ群でモデルの学習を行う